### ISSUE TITLE
sbt build eclipse fail when trying to resolve bigdata dependency

### ISSUE THREAD

**Issue by cmungall** [phenoscape/phenoscape-owl-tools#11]
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.bigdata#bigdata;1.3.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.bigdata:bigdata:1.3.4 (/Users/cjm/repos/phenoscape-owl-tools/build.sbt#L32-47)
[warn]            +- org.phenoscape:kb-owl-tools_2.11:1.3
sbt.ResolveException: unresolved dependency: com.bigdata#bigdata;1.3.4: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:243)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:158)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:124)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
...
```

without this, the some source will not compile as org.openrdf is required

Is it not possible to have a separate dependency on org.openrdf and have bigdata be optional?

**Comment by balhoff** [comment]
I just cloned fresh from GitHub and ran `sbt compile` without error. Did you edit the build file somehow?

**Comment by cmungall** [comment]
Tried a fresh checkout, same issue

@jnguyenx can you try?

**Comment by jnguyenx** [comment]
Same error

[warn]     Note: Unresolved dependencies path:
[warn]         com.bigdata:bigdata:1.3.4
(/home/jnguyenxuan/workspace/phenoscape-owl-tools/build.sbt#L32-47)
[warn]           +- org.phenoscape:kb-owl-tools_2.11:1.3
sbt.ResolveException: unresolved dependency: com.bigdata#bigdata;1.3.4: not
found

**Comment by cmungall** [comment]
And again, after upgrading sbt from 0.13.7 to 0.13.9

**Comment by balhoff** [comment]
I don't think you need to explicitly upgrade your sbt, since it is specified in the project (it automatically downloads the right version). But the one thing not specified in the build file is the sbt-eclipse plugin. I have 4.0.0, specified in `~/.sbt/0.13/plugins/plugins.sbt`:

```scala
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")
```

Could that be the difference?

**Comment by jnguyenx** [comment]
I ran "sbt clean compile". So the build fails to fetch this bigdata
dependency.

My guess is that this dependency has been cached in your local repo.
When I go to the bigdata repo defined in the build.sbt I get a 404.
http://systap.com/maven/releases/

I've just realized that www has to be added in the URL. So the correct path
is http://www.systap.com/maven/releases/

**Comment by balhoff** [comment]
@jnguyenx you figured it out. I removed bigdata from my ivy cache and had the same problem. I updated the URL for the bigdata maven repository: 006dff759e08a3bbaf9ca67fd1b346cafff87acd

@cmungall I am guessing it will work for you now.

**Comment by balhoff** [comment]
I think this is working for everyone now.
