### ISSUE TITLE
Convert spreadsheet annotations to OWL

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-owl-tools#25]
Write an importer to convert annotations from spreadsheet .xls format to OWL, and save in NeXML format

The Excel dataset for conversion is here:
https://www.dropbox.com/s/ekc4xqg436becyi/Dillman_etal_2016_annotations.xls?dl=0

@balhoff or @Shalsh23

**Comment by balhoff** [comment]
This was completed.
